#!/usr/bin/env bash
# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > index.html
sudo mv index.html /var/www/html
rdr="\\\trewrite ^/redirectme_me https://media1.tenor.com/images/e925ae1430bc72230747042137c5e057/tenor.gif?itemid=10222299 permanent;"
sudo sed -i "42i $rdr" /etc/nginx/sites-available/default
sudo service nginx restart