#!/usr/bin/env bash
# Configures ubuntu server with specific values
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.02/ ~/hostos.new
echo 8.8.8.8 'facebook.com' >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
